### ISSUE TITLE
Get started with cost model experiments

### ISSUE THREAD

**Issue by merrymercy** [tlc-pack/tenset#1]
# Get started 
This tutorial contains a minimal example of training a cost model and using it for search.

# Dataset
## Install and Download
1. Build and install this repo following the [install guide](https://tvm.apache.org/docs/install/index.html) of TVM.
2. Download dataset file.
    - You can download it from [google drive](https://drive.google.com/file/d/1hciRGyXcGY9fK_owgvlJow8P_l8xYIVJ/view?usp=sharing)
    - Or you can use the command line
    ```
    pip3 install gdown
    gdown https://drive.google.com/uc?id=1hciRGyXcGY9fK_owgvlJow8P_l8xYIVJ
    ```
3. Put `dataset_v3.1.zip` under `tvm-cost-model/scripts` and run `unzip dataset_v3.1.zip`
A new folder `dataset` will appear in `tvm-cost-model/scripts`.

## Dataset Content
see this [readme](https://github.com/merrymercy/tvm-cost-model/tree/main/scripts#dataset-organization)

# Example experiment

## Train a cost model and use it for search
Go to `tvm-cost-model/scripts`.

1. Make a dataset
You can either 
  - create a sampled smaller dataset for fast experiments.
```
python3 make_dataset.py --logs dataset/measure_records/e5-2673/*.json --sample-in-files 100
```
  - create a complete dataset by using all files. This takes a longer time and requires more memory.
```
python3 make_dataset.py --logs dataset/measure_records/e5-2673/*.json
```
2. Train a cost model
```
python3 train_model.py
```
3. Use the model for search
```
python3 tune_network.py --network resnet_50 --n-trials 100 --cost-model xgb-no-update --load-model xgb.pkl
```

# References
- [Learning to Optimize Tensor Programs (NeurIPS 18)](https://arxiv.org/abs/1805.08166)
- [Ansor : Generating High-Performance Tensor Programs for Deep Learning (OSDI 20)](https://arxiv.org/abs/2006.06762)
- [Value Learning For Throughput Optimization of Deep Neural Networks (MLSys 21)](https://proceedings.mlsys.org/paper/2021/file/73278a4a86960eeb576a8fd4c9ec6997-Paper.pdf)
- [MetaTune: Meta-Learning Based Cost Model for Fast and Efficient Auto-tuning Frameworks](https://arxiv.org/abs/2102.04199)
- [A Deep Learning Based Cost Model for Automatic Code Optimization (MLSys 21)](https://proceedings.mlsys.org/paper/2021/file/3def184ad8f4755ff269862ea77393dd-Paper.pdf)
- [Learned TPU Cost Model for XLA Tensor Programs (MLSys 21)](https://arxiv.org/pdf/2008.01040.pdf)
- [Ithemal: Accurate, Portable and Fast Basic Block Throughput Estimation using Deep Neural Networks (ICML 19)](https://arxiv.org/abs/1808.07412)
- [Learning to Represent Programs with Graphs (ICLR 18)](https://arxiv.org/abs/1711.00740)
- [Learning to Optimize Halide with Tree Search and Random Programs (SIGGRAPH 19)](https://halide-lang.org/papers/halide_autoscheduler_2019.pdf)
- [CS 330: Deep Multi-Task and Meta Learning](http://cs330.stanford.edu/fall2019/)

**Comment by catmaohphp** [comment]
The dataset file is not available for download now.

**Comment by merrymercy** [comment]
This issue is outdated. see https://github.com/tlc-pack/tenset/blob/main/docs/get_started_with_cost_model_experiments.md

**Comment by merrymercy** [comment]
@catmaohphp  This issue is outdated. see https://github.com/tlc-pack/tenset/blob/main/docs/get_started_with_cost_model_experiments.md

**Comment by catmaohphp** [comment]
Thank you for your quick response!
