### ISSUE TITLE
Meet error running measure_program.py on TX2 

### ISSUE THREAD

**Issue by Kyrie-Zhao** [tlc-pack/tenset#26]
I encounter two bugs when collecting data on NVIDIA TX2. The settings are:

**Device:** NVIDIA TX2 (cuda gpu)
**Model:**     
for batch_size in [1]:
        for image_size in [256]:
            for layer in [18]:
                network_keys.append((f'resnet_{layer}',
                                    [(batch_size, 3, image_size, image_size)]))
**shell:**
python measure_programs.py --target "cuda -keys=cudagpu -arch=SM_62" --target-host="llvm"

**The meeting bugs are:**
root@kyrie-desktop:/home/kyrie/Desktop/ijcai/tenset/scripts# python measure_programs.py --target "cuda -keys=cudagpu -arch=SM_62" --target-host="llvm"

Load all tasks...
===== task: 0     programs: 0/193 =====
Get 128 programs to measure:
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
Time elapsed for measurement: 708.33 s
===== task: 0     programs: 128/193 =====
Get 65 programs to measure:
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
........*T*T*T*T*T*T*T*T
[10:37:55] /home/kyrie/Desktop/ijcai/tenset/src/auto_scheduler/measure.cc:337: warning: Too many errors happened during tuning. Switching to debug mode.

........*T*T*T*T*T*T*T*T
==================================================
No: 153    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079882.82)
==================================================
Placeholder:

==================================================
No: 154    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079888.05)
==================================================
Placeholder:

==================================================
No: 155    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079893.27)
==================================================
Placeholder:

==================================================
No: 156    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079898.49)
==================================================
Placeholder:

==================================================
No: 157    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.01, Tstamp:1636079903.71)
==================================================
Placeholder:

==================================================
No: 158    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636079908.93)
==================================================
Placeholder:

==================================================
No: 159    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636079914.15)
==================================================
Placeholder:

==================================================
No: 160    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:5.99, Tstamp:1636079919.38)
==================================================
Placeholder:

[10:38:39] /home/kyrie/Desktop/ijcai/tenset/src/auto_scheduler/measure.cc:337: warning: Too many errors happened during tuning. Switching to debug mode.

........*T*T*T*T*T*T*T*T
==================================================
No: 161    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079927.01)
==================================================
Placeholder:

==================================================
No: 162    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:5.99, Tstamp:1636079932.25)
==================================================
Placeholder:

==================================================
No: 163    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.03, Tstamp:1636079937.47)
==================================================
Placeholder:

==================================================
No: 164    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:5.98, Tstamp:1636079942.69)
==================================================
Placeholder:

==================================================
No: 165    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636079947.91)
==================================================
Placeholder:

==================================================
No: 166    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079953.13)
==================================================
Placeholder:

==================================================
No: 167    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.03, Tstamp:1636079958.34)
==================================================
Placeholder:

==================================================
No: 168    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636079963.57)
==================================================
Placeholder:

[10:39:23] /home/kyrie/Desktop/ijcai/tenset/src/auto_scheduler/measure.cc:337: warning: Too many errors happened during tuning. Switching to debug mode.

........*T*T*T*T*T*T*T*T
==================================================
No: 169    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079971.21)
==================================================
Placeholder:

==================================================
No: 170    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079976.44)
==================================================
Placeholder:

==================================================
No: 171    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:5.99, Tstamp:1636079981.67)
==================================================
Placeholder:

==================================================
No: 172    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636079986.89)
==================================================
Placeholder:

==================================================
No: 173    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636079992.11)
==================================================
Placeholder:

==================================================
No: 174    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.03, Tstamp:1636079997.34)
==================================================
Placeholder:

==================================================
No: 175    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636080002.56)
==================================================
Placeholder:

==================================================
No: 176    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636080007.78)
==================================================
Placeholder:

[10:40:07] /home/kyrie/Desktop/ijcai/tenset/src/auto_scheduler/measure.cc:337: warning: Too many errors happened during tuning. Switching to debug mode.

........*T*T*T*T*T*T*T*T
==================================================
No: 177    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.01, Tstamp:1636080015.53)
==================================================
Placeholder:

==================================================
No: 178    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.04, Tstamp:1636080020.75)
==================================================
Placeholder:

==================================================
No: 179    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:5.97, Tstamp:1636080025.98)
==================================================
Placeholder:

==================================================
No: 180    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.01, Tstamp:1636080031.20)
==================================================
Placeholder:

==================================================
No: 181    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.01, Tstamp:1636080036.43)
==================================================
Placeholder:

==================================================
No: 182    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636080041.65)
==================================================
Placeholder:

==================================================
No: 183    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.01, Tstamp:1636080046.86)
==================================================
Placeholder:

==================================================
No: 184    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.03, Tstamp:1636080052.08)
==================================================
Placeholder:

[10:40:52] /home/kyrie/Desktop/ijcai/tenset/src/auto_scheduler/measure.cc:337: warning: Too many errors happened during tuning. Switching to debug mode.

........*T*T*T*T*T*T*T*T
==================================================
No: 185    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.00, Tstamp:1636080059.73)
==================================================
Placeholder:

==================================================
No: 186    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:5.99, Tstamp:1636080064.95)
==================================================
Placeholder:

==================================================
No: 187    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.01, Tstamp:1636080070.16)
==================================================
Placeholder:

==================================================
No: 188    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:5.99, Tstamp:1636080075.38)
==================================================
Placeholder:

==================================================
No: 189    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636080080.60)
==================================================
Placeholder:

==================================================
No: 190    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.02, Tstamp:1636080085.83)

==================================================
Placeholder:

==================================================
No: 191    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.01, Tstamp:1636080091.05)
==================================================
Placeholder:

==================================================
No: 192    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:6.01, Tstamp:1636080096.28)
==================================================
Placeholder:

[10:41:36] /home/kyrie/Desktop/ijcai/tenset/src/auto_scheduler/measure.cc:337: warning: Too many errors happened during tuning. Switching to debug mode.

.*T
==================================================
No: 193    GFLOPS: 0.00 / 0.00    results: MeasureResult(error_type:RunTimeoutError, error_msg:, all_cost:5.87, Tstamp:1636080102.51)
==================================================
Placeholder:

[10:41:42] /home/kyrie/Desktop/ijcai/tenset/src/auto_scheduler/measure.cc:337: warning: Too many errors happened during tuning. Switching to debug mode.

**The error starts to happen at the 153th program for each task.**

**Another bug happens later**:
No: 3889	GFLOPS: 0.00 / 0.00	results: MeasureResult(error_type:CompileHostError, error_msg:Traceback (most recent call last):
  File "/home/kyrie/Desktop/ijcai/tenset/python/tvm/auto_scheduler/measure.py", line 653, in _timed_func
    sch, args, target=task.target, target_host=task.target_host
  File "/home/kyrie/Desktop/ijcai/tenset/python/tvm/
...
ir::VarNode const*, tvm::PrimExpr)
  0: tvm::codegen::CodeGenCUDA::PrintType(tvm::runtime::DataType, std::ostream&)
  File "/home/kyrie/Desktop/ijcai/tenset/src/target/source/codegen_cuda.cc", line 351
TVMError: Cannot convert type float32x32 to CUDA type
, all_cost:0.68, Tstamp:1636105300.67)
==================================================
Placeholder:

**Comment by merrymercy** [comment]
1. Do you use this branch to dump programs ? https://github.com/tlc-pack/tenset/pull/4
2. Is your RPC connection stable?
3. Try to teak these parameters https://github.com/tlc-pack/tenset/blob/62f0c20cc6e6b085e0c22bbfa2e241909af19a5d/scripts/measure_programs.py#L103-L117. For example, set a higher timeout
