### ISSUE TITLE
Is there a way to look at the generated programs?

### ISSUE THREAD

**Issue by akash-isu** [tlc-pack/tenset#36]
Is there a way to look at the generated programs/subgraphs? For example, if there is some CUDA/Python code that's generated and measured, is it possible to look at that code file?

Apologies, if the answer to this is obvious. Really new to TVM.

Thanks,
Akash

**Comment by merrymercy** [comment]
https://github.com/tlc-pack/tenset#inspect-tasks-and-programs-in-the-dataset
